# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BinServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BinServer.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x42inServer.proto\x12\x06protos\x1a\x1cgoogle/api/annotations.proto\"<\n\x0cMotorRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05motor\x18\x02 \x01(\x05\x12\x0c\n\x04\x64irc\x18\x03 \x01(\x05\" \n\rStatusRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\":\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\r\n\x05\x61ngel\x18\x02 \x01(\x02\x12\x0c\n\x04temp\x18\x03 \x01(\x02\"\x1b\n\nImageReply\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x06\n\x04NULL2\x81\x02\n\nBinService\x12I\n\x08\x42inMotor\x12\x14.protos.MotorRequest\x1a\x0c.protos.NULL\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/autobin/binmotor\x12S\n\tBinStatus\x12\x15.protos.StatusRequest\x1a\x13.protos.StatusReply\"\x1a\x82\xd3\xe4\x93\x02\x14\"\x0f/autobin/status:\x01*\x12S\n\x08\x42inImage\x12\x15.protos.StatusRequest\x1a\x12.protos.ImageReply\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x11/autobin/binimage:\x01*b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_MOTORREQUEST = _descriptor.Descriptor(
  name='MotorRequest',
  full_name='protos.MotorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='protos.MotorRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor', full_name='protos.MotorRequest.motor', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dirc', full_name='protos.MotorRequest.dirc', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=117,
)


_STATUSREQUEST = _descriptor.Descriptor(
  name='StatusRequest',
  full_name='protos.StatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='protos.StatusRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=151,
)


_STATUSREPLY = _descriptor.Descriptor(
  name='StatusReply',
  full_name='protos.StatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='protos.StatusReply.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angel', full_name='protos.StatusReply.angel', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='protos.StatusReply.temp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=211,
)


_IMAGEREPLY = _descriptor.Descriptor(
  name='ImageReply',
  full_name='protos.ImageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='protos.ImageReply.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=240,
)


_NULL = _descriptor.Descriptor(
  name='NULL',
  full_name='protos.NULL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=248,
)

DESCRIPTOR.message_types_by_name['MotorRequest'] = _MOTORREQUEST
DESCRIPTOR.message_types_by_name['StatusRequest'] = _STATUSREQUEST
DESCRIPTOR.message_types_by_name['StatusReply'] = _STATUSREPLY
DESCRIPTOR.message_types_by_name['ImageReply'] = _IMAGEREPLY
DESCRIPTOR.message_types_by_name['NULL'] = _NULL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotorRequest = _reflection.GeneratedProtocolMessageType('MotorRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOTORREQUEST,
  '__module__' : 'BinServer_pb2'
  # @@protoc_insertion_point(class_scope:protos.MotorRequest)
  })
_sym_db.RegisterMessage(MotorRequest)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATUSREQUEST,
  '__module__' : 'BinServer_pb2'
  # @@protoc_insertion_point(class_scope:protos.StatusRequest)
  })
_sym_db.RegisterMessage(StatusRequest)

StatusReply = _reflection.GeneratedProtocolMessageType('StatusReply', (_message.Message,), {
  'DESCRIPTOR' : _STATUSREPLY,
  '__module__' : 'BinServer_pb2'
  # @@protoc_insertion_point(class_scope:protos.StatusReply)
  })
_sym_db.RegisterMessage(StatusReply)

ImageReply = _reflection.GeneratedProtocolMessageType('ImageReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREPLY,
  '__module__' : 'BinServer_pb2'
  # @@protoc_insertion_point(class_scope:protos.ImageReply)
  })
_sym_db.RegisterMessage(ImageReply)

NULL = _reflection.GeneratedProtocolMessageType('NULL', (_message.Message,), {
  'DESCRIPTOR' : _NULL,
  '__module__' : 'BinServer_pb2'
  # @@protoc_insertion_point(class_scope:protos.NULL)
  })
_sym_db.RegisterMessage(NULL)



_BINSERVICE = _descriptor.ServiceDescriptor(
  name='BinService',
  full_name='protos.BinService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=251,
  serialized_end=508,
  methods=[
  _descriptor.MethodDescriptor(
    name='BinMotor',
    full_name='protos.BinService.BinMotor',
    index=0,
    containing_service=None,
    input_type=_MOTORREQUEST,
    output_type=_NULL,
    serialized_options=_b('\202\323\344\223\002\023\022\021/autobin/binmotor'),
  ),
  _descriptor.MethodDescriptor(
    name='BinStatus',
    full_name='protos.BinService.BinStatus',
    index=1,
    containing_service=None,
    input_type=_STATUSREQUEST,
    output_type=_STATUSREPLY,
    serialized_options=_b('\202\323\344\223\002\024\"\017/autobin/status:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='BinImage',
    full_name='protos.BinService.BinImage',
    index=2,
    containing_service=None,
    input_type=_STATUSREQUEST,
    output_type=_IMAGEREPLY,
    serialized_options=_b('\202\323\344\223\002\026\"\021/autobin/binimage:\001*'),
  ),
])
_sym_db.RegisterServiceDescriptor(_BINSERVICE)

DESCRIPTOR.services_by_name['BinService'] = _BINSERVICE

# @@protoc_insertion_point(module_scope)
