# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.BinServer_pb2 as BinServer__pb2


class BinServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BinMotor = channel.unary_unary(
        '/protos.BinService/BinMotor',
        request_serializer=BinServer__pb2.MotorRequest.SerializeToString,
        response_deserializer=BinServer__pb2.NULL.FromString,
        )
    self.BinStatus = channel.unary_unary(
        '/protos.BinService/BinStatus',
        request_serializer=BinServer__pb2.StatusRequest.SerializeToString,
        response_deserializer=BinServer__pb2.StatusReply.FromString,
        )
    self.BinImage = channel.unary_unary(
        '/protos.BinService/BinImage',
        request_serializer=BinServer__pb2.StatusRequest.SerializeToString,
        response_deserializer=BinServer__pb2.ImageReply.FromString,
        )


class BinServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BinMotor(self, request, context):
    """手动控制电机调用
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BinStatus(self, request, context):
    """状态获取
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BinImage(self, request, context):
    """垃圾桶当前图像
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BinServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BinMotor': grpc.unary_unary_rpc_method_handler(
          servicer.BinMotor,
          request_deserializer=BinServer__pb2.MotorRequest.FromString,
          response_serializer=BinServer__pb2.NULL.SerializeToString,
      ),
      'BinStatus': grpc.unary_unary_rpc_method_handler(
          servicer.BinStatus,
          request_deserializer=BinServer__pb2.StatusRequest.FromString,
          response_serializer=BinServer__pb2.StatusReply.SerializeToString,
      ),
      'BinImage': grpc.unary_unary_rpc_method_handler(
          servicer.BinImage,
          request_deserializer=BinServer__pb2.StatusRequest.FromString,
          response_serializer=BinServer__pb2.ImageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.BinService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
