# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waste.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='waste.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bwaste.proto\x12\x06protos\x1a\x1cgoogle/api/annotations.proto\"E\n\x0cWasteRequest\x12\x0e\n\x06\x62in_id\x18\x01 \x01(\t\x12\x10\n\x08waste_id\x18\x02 \x01(\t\x12\x13\n\x0bwaste_image\x18\x03 \x01(\x0c\"\x1c\n\nWasteReply\x12\x0e\n\x06res_id\x18\x01 \x01(\x03\"\x06\n\x04Null\"4\n\x10\x42inStatusRequest\x12\x10\n\x08waste_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x05\x32\xb7\x01\n\x0cWasteService\x12S\n\x0bWasteDetect\x12\x14.protos.WasteRequest\x1a\x12.protos.WasteReply\"\x1a\x82\xd3\xe4\x93\x02\x14\"\x0f/autobin/detect:\x01*\x12R\n\tBinStatus\x12\x18.protos.BinStatusRequest\x1a\x0c.protos.Null\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x12/autobin/binstatus:\x01*b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_WASTEREQUEST = _descriptor.Descriptor(
  name='WasteRequest',
  full_name='protos.WasteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bin_id', full_name='protos.WasteRequest.bin_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='waste_id', full_name='protos.WasteRequest.waste_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='waste_image', full_name='protos.WasteRequest.waste_image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=122,
)


_WASTEREPLY = _descriptor.Descriptor(
  name='WasteReply',
  full_name='protos.WasteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res_id', full_name='protos.WasteReply.res_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=152,
)


_NULL = _descriptor.Descriptor(
  name='Null',
  full_name='protos.Null',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=160,
)


_BINSTATUSREQUEST = _descriptor.Descriptor(
  name='BinStatusRequest',
  full_name='protos.BinStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='waste_id', full_name='protos.BinStatusRequest.waste_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='protos.BinStatusRequest.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=214,
)

DESCRIPTOR.message_types_by_name['WasteRequest'] = _WASTEREQUEST
DESCRIPTOR.message_types_by_name['WasteReply'] = _WASTEREPLY
DESCRIPTOR.message_types_by_name['Null'] = _NULL
DESCRIPTOR.message_types_by_name['BinStatusRequest'] = _BINSTATUSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WasteRequest = _reflection.GeneratedProtocolMessageType('WasteRequest', (_message.Message,), {
  'DESCRIPTOR' : _WASTEREQUEST,
  '__module__' : 'waste_pb2'
  # @@protoc_insertion_point(class_scope:protos.WasteRequest)
  })
_sym_db.RegisterMessage(WasteRequest)

WasteReply = _reflection.GeneratedProtocolMessageType('WasteReply', (_message.Message,), {
  'DESCRIPTOR' : _WASTEREPLY,
  '__module__' : 'waste_pb2'
  # @@protoc_insertion_point(class_scope:protos.WasteReply)
  })
_sym_db.RegisterMessage(WasteReply)

Null = _reflection.GeneratedProtocolMessageType('Null', (_message.Message,), {
  'DESCRIPTOR' : _NULL,
  '__module__' : 'waste_pb2'
  # @@protoc_insertion_point(class_scope:protos.Null)
  })
_sym_db.RegisterMessage(Null)

BinStatusRequest = _reflection.GeneratedProtocolMessageType('BinStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _BINSTATUSREQUEST,
  '__module__' : 'waste_pb2'
  # @@protoc_insertion_point(class_scope:protos.BinStatusRequest)
  })
_sym_db.RegisterMessage(BinStatusRequest)



_WASTESERVICE = _descriptor.ServiceDescriptor(
  name='WasteService',
  full_name='protos.WasteService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=217,
  serialized_end=400,
  methods=[
  _descriptor.MethodDescriptor(
    name='WasteDetect',
    full_name='protos.WasteService.WasteDetect',
    index=0,
    containing_service=None,
    input_type=_WASTEREQUEST,
    output_type=_WASTEREPLY,
    serialized_options=_b('\202\323\344\223\002\024\"\017/autobin/detect:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='BinStatus',
    full_name='protos.WasteService.BinStatus',
    index=1,
    containing_service=None,
    input_type=_BINSTATUSREQUEST,
    output_type=_NULL,
    serialized_options=_b('\202\323\344\223\002\027\"\022/autobin/binstatus:\001*'),
  ),
])
_sym_db.RegisterServiceDescriptor(_WASTESERVICE)

DESCRIPTOR.services_by_name['WasteService'] = _WASTESERVICE

# @@protoc_insertion_point(module_scope)
