// Code generated by protoc-gen-go. DO NOT EDIT.
// source: waste.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WasteRequest struct {
	BinId                string   `protobuf:"bytes,1,opt,name=bin_id,json=binId,proto3" json:"bin_id,omitempty"`
	WasteImage           string   `protobuf:"bytes,2,opt,name=waste_image,json=wasteImage,proto3" json:"waste_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WasteRequest) Error() string {
	panic("implement me")
}

func (m *WasteRequest) Reset()         { *m = WasteRequest{} }
func (m *WasteRequest) String() string { return proto.CompactTextString(m) }
func (*WasteRequest) ProtoMessage()    {}
func (*WasteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2ebfcf672cd925, []int{0}
}

func (m *WasteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasteRequest.Unmarshal(m, b)
}
func (m *WasteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasteRequest.Marshal(b, m, deterministic)
}
func (m *WasteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasteRequest.Merge(m, src)
}
func (m *WasteRequest) XXX_Size() int {
	return xxx_messageInfo_WasteRequest.Size(m)
}
func (m *WasteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WasteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WasteRequest proto.InternalMessageInfo

func (m *WasteRequest) GetBinId() string {
	if m != nil {
		return m.BinId
	}
	return ""
}

func (m *WasteRequest) GetWasteImage() string {
	if m != nil {
		return m.WasteImage
	}
	return ""
}

type WasteReply struct {
	ResId                int64    `protobuf:"varint,1,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WasteReply) Reset()         { *m = WasteReply{} }
func (m *WasteReply) String() string { return proto.CompactTextString(m) }
func (*WasteReply) ProtoMessage()    {}
func (*WasteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2ebfcf672cd925, []int{1}
}

func (m *WasteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasteReply.Unmarshal(m, b)
}
func (m *WasteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasteReply.Marshal(b, m, deterministic)
}
func (m *WasteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasteReply.Merge(m, src)
}
func (m *WasteReply) XXX_Size() int {
	return xxx_messageInfo_WasteReply.Size(m)
}
func (m *WasteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WasteReply.DiscardUnknown(m)
}

var xxx_messageInfo_WasteReply proto.InternalMessageInfo

func (m *WasteReply) GetResId() int64 {
	if m != nil {
		return m.ResId
	}
	return 0
}

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2ebfcf672cd925, []int{2}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type BinStatusRequest struct {
	BinId                int32    `protobuf:"varint,1,opt,name=bin_id,json=binId,proto3" json:"bin_id,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinStatusRequest) Reset()         { *m = BinStatusRequest{} }
func (m *BinStatusRequest) String() string { return proto.CompactTextString(m) }
func (*BinStatusRequest) ProtoMessage()    {}
func (*BinStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2ebfcf672cd925, []int{3}
}

func (m *BinStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinStatusRequest.Unmarshal(m, b)
}
func (m *BinStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinStatusRequest.Marshal(b, m, deterministic)
}
func (m *BinStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinStatusRequest.Merge(m, src)
}
func (m *BinStatusRequest) XXX_Size() int {
	return xxx_messageInfo_BinStatusRequest.Size(m)
}
func (m *BinStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BinStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BinStatusRequest proto.InternalMessageInfo

func (m *BinStatusRequest) GetBinId() int32 {
	if m != nil {
		return m.BinId
	}
	return 0
}

func (m *BinStatusRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type BinRegisterRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinRegisterRequest) Reset()         { *m = BinRegisterRequest{} }
func (m *BinRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*BinRegisterRequest) ProtoMessage()    {}
func (*BinRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2ebfcf672cd925, []int{4}
}

func (m *BinRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinRegisterRequest.Unmarshal(m, b)
}
func (m *BinRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinRegisterRequest.Marshal(b, m, deterministic)
}
func (m *BinRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinRegisterRequest.Merge(m, src)
}
func (m *BinRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_BinRegisterRequest.Size(m)
}
func (m *BinRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BinRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BinRegisterRequest proto.InternalMessageInfo

func (m *BinRegisterRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type BinRegisterReply struct {
	BinId                int32    `protobuf:"varint,1,opt,name=bin_id,json=binId,proto3" json:"bin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinRegisterReply) Reset()         { *m = BinRegisterReply{} }
func (m *BinRegisterReply) String() string { return proto.CompactTextString(m) }
func (*BinRegisterReply) ProtoMessage()    {}
func (*BinRegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2ebfcf672cd925, []int{5}
}

func (m *BinRegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinRegisterReply.Unmarshal(m, b)
}
func (m *BinRegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinRegisterReply.Marshal(b, m, deterministic)
}
func (m *BinRegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinRegisterReply.Merge(m, src)
}
func (m *BinRegisterReply) XXX_Size() int {
	return xxx_messageInfo_BinRegisterReply.Size(m)
}
func (m *BinRegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BinRegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_BinRegisterReply proto.InternalMessageInfo

func (m *BinRegisterReply) GetBinId() int32 {
	if m != nil {
		return m.BinId
	}
	return 0
}

func init() {
	proto.RegisterType((*WasteRequest)(nil), "protos.WasteRequest")
	proto.RegisterType((*WasteReply)(nil), "protos.WasteReply")
	proto.RegisterType((*Null)(nil), "protos.Null")
	proto.RegisterType((*BinStatusRequest)(nil), "protos.BinStatusRequest")
	proto.RegisterType((*BinRegisterRequest)(nil), "protos.BinRegisterRequest")
	proto.RegisterType((*BinRegisterReply)(nil), "protos.BinRegisterReply")
}

func init() { proto.RegisterFile("waste.proto", fileDescriptor_2e2ebfcf672cd925) }

var fileDescriptor_2e2ebfcf672cd925 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x4b, 0xfb, 0x30,
	0x18, 0xc7, 0xe9, 0x7e, 0xbf, 0x56, 0xf6, 0x6c, 0xa0, 0x86, 0xb9, 0x95, 0x32, 0x51, 0xe2, 0x45,
	0x07, 0xae, 0xa0, 0xb7, 0xdd, 0x1c, 0x22, 0xf4, 0xe2, 0xa1, 0x3b, 0x78, 0x1c, 0xe9, 0xfa, 0x50,
	0x02, 0x35, 0xa9, 0x49, 0xaa, 0xec, 0xea, 0x5b, 0xf0, 0xe6, 0xdb, 0xf2, 0x2d, 0xf8, 0x42, 0xa4,
	0x69, 0xbb, 0x8d, 0xb1, 0x53, 0x79, 0xfe, 0xe4, 0xf3, 0x4d, 0x3f, 0x04, 0x7a, 0x1f, 0x4c, 0x1b,
	0x9c, 0x16, 0x4a, 0x1a, 0x49, 0x3c, 0xfb, 0xd1, 0xc1, 0x38, 0x93, 0x32, 0xcb, 0x31, 0x64, 0x05,
	0x0f, 0x99, 0x10, 0xd2, 0x30, 0xc3, 0xa5, 0xd0, 0xf5, 0x16, 0x7d, 0x82, 0xfe, 0x4b, 0x75, 0x28,
	0xc6, 0xb7, 0x12, 0xb5, 0x21, 0x67, 0xe0, 0x25, 0x5c, 0x2c, 0x79, 0xea, 0x3b, 0x97, 0xce, 0x75,
	0x37, 0x76, 0x13, 0x2e, 0xa2, 0x94, 0x5c, 0x34, 0xec, 0x25, 0x7f, 0x65, 0x19, 0xfa, 0x1d, 0x3b,
	0x03, 0xdb, 0x8a, 0xaa, 0x0e, 0xbd, 0x02, 0x68, 0x38, 0x45, 0xbe, 0xae, 0x28, 0x0a, 0x75, 0x4b,
	0xf9, 0x17, 0xbb, 0x0a, 0x75, 0x94, 0x52, 0x0f, 0xfe, 0x3f, 0x97, 0x79, 0x4e, 0x1f, 0xe0, 0x64,
	0xce, 0xc5, 0xc2, 0x30, 0x53, 0xea, 0xc3, 0xc1, 0x6e, 0x1b, 0x3c, 0x04, 0x4f, 0xdb, 0x3d, 0x9b,
	0xe9, 0xc6, 0x4d, 0x45, 0x6f, 0x81, 0xcc, 0xb9, 0x88, 0x31, 0xe3, 0xda, 0xa0, 0x6a, 0x21, 0x23,
	0x38, 0x2a, 0x35, 0xaa, 0x2d, 0xc5, 0xab, 0xca, 0x28, 0xa5, 0x37, 0x36, 0x71, 0xbb, 0xde, 0x5c,
	0xf2, 0x40, 0xe2, 0xdd, 0x77, 0xa7, 0x51, 0xb2, 0x40, 0xf5, 0xce, 0x57, 0x48, 0x16, 0xd0, 0xb3,
	0xf5, 0x23, 0x1a, 0x5c, 0x19, 0x32, 0xa8, 0xcd, 0xe9, 0xe9, 0xae, 0xb7, 0x80, 0xec, 0x75, 0x8b,
	0x7c, 0x4d, 0x83, 0xcf, 0x9f, 0xdf, 0xaf, 0xce, 0x80, 0x1e, 0x87, 0xac, 0x34, 0x32, 0xe1, 0x22,
	0x4c, 0x2d, 0x62, 0xe6, 0x4c, 0x48, 0x0c, 0xdd, 0x8d, 0x02, 0xe2, 0xb7, 0x87, 0xf7, 0xad, 0x04,
	0xfd, 0x76, 0x62, 0xbd, 0x9d, 0x5b, 0xe0, 0x88, 0x92, 0x0d, 0x30, 0xe1, 0xa2, 0x16, 0x52, 0x31,
	0x19, 0xf4, 0x76, 0x7e, 0x92, 0x04, 0x3b, 0xd4, 0x3d, 0x51, 0x81, 0x7f, 0x70, 0x56, 0x5d, 0x7a,
	0x6c, 0x33, 0x86, 0xf4, 0x74, 0x93, 0xa1, 0x9a, 0xf9, 0xcc, 0x99, 0x24, 0xf5, 0xa3, 0xba, 0xff,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x20, 0xfb, 0x2d, 0x6a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WasteServiceClient is the client API for WasteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WasteServiceClient interface {
	// 传输实时图片 返回识别结果
	WasteDetect(ctx context.Context, in *WasteRequest, opts ...grpc.CallOption) (*WasteReply, error)
	// 状态上报
	BinStatus(ctx context.Context, in *BinStatusRequest, opts ...grpc.CallOption) (*Null, error)
	// 垃圾桶注册
	BinRegister(ctx context.Context, in *BinRegisterRequest, opts ...grpc.CallOption) (*BinRegisterReply, error)
}

type wasteServiceClient struct {
	cc *grpc.ClientConn
}

func NewWasteServiceClient(cc *grpc.ClientConn) WasteServiceClient {
	return &wasteServiceClient{cc}
}

func (c *wasteServiceClient) WasteDetect(ctx context.Context, in *WasteRequest, opts ...grpc.CallOption) (*WasteReply, error) {
	out := new(WasteReply)
	err := c.cc.Invoke(ctx, "/protos.WasteService/WasteDetect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wasteServiceClient) BinStatus(ctx context.Context, in *BinStatusRequest, opts ...grpc.CallOption) (*Null, error) {
	out := new(Null)
	err := c.cc.Invoke(ctx, "/protos.WasteService/BinStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wasteServiceClient) BinRegister(ctx context.Context, in *BinRegisterRequest, opts ...grpc.CallOption) (*BinRegisterReply, error) {
	out := new(BinRegisterReply)
	err := c.cc.Invoke(ctx, "/protos.WasteService/BinRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WasteServiceServer is the server API for WasteService service.
type WasteServiceServer interface {
	// 传输实时图片 返回识别结果
	WasteDetect(context.Context, *WasteRequest) (*WasteReply, error)
	// 状态上报
	BinStatus(context.Context, *BinStatusRequest) (*Null, error)
	// 垃圾桶注册
	BinRegister(context.Context, *BinRegisterRequest) (*BinRegisterReply, error)
}

// UnimplementedWasteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWasteServiceServer struct {
}

func (*UnimplementedWasteServiceServer) WasteDetect(ctx context.Context, req *WasteRequest) (*WasteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WasteDetect not implemented")
}
func (*UnimplementedWasteServiceServer) BinStatus(ctx context.Context, req *BinStatusRequest) (*Null, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BinStatus not implemented")
}
func (*UnimplementedWasteServiceServer) BinRegister(ctx context.Context, req *BinRegisterRequest) (*BinRegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BinRegister not implemented")
}

func RegisterWasteServiceServer(s *grpc.Server, srv WasteServiceServer) {
	s.RegisterService(&_WasteService_serviceDesc, srv)
}

func _WasteService_WasteDetect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WasteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasteServiceServer).WasteDetect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.WasteService/WasteDetect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasteServiceServer).WasteDetect(ctx, req.(*WasteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WasteService_BinStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasteServiceServer).BinStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.WasteService/BinStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasteServiceServer).BinStatus(ctx, req.(*BinStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WasteService_BinRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasteServiceServer).BinRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.WasteService/BinRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasteServiceServer).BinRegister(ctx, req.(*BinRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WasteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.WasteService",
	HandlerType: (*WasteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WasteDetect",
			Handler:    _WasteService_WasteDetect_Handler,
		},
		{
			MethodName: "BinStatus",
			Handler:    _WasteService_BinStatus_Handler,
		},
		{
			MethodName: "BinRegister",
			Handler:    _WasteService_BinRegister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "waste.proto",
}
